biz_db:
    image: mysql:latest
    ports:
        - "3333:3306"
    volumes:
        - /var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=my-secret-pw

biz_ecosystem:
    image: fiware/bae-test
    ports:
        - "8000:8000"
    links:
        - biz_db
    volumes:
        - /your/bills/path:/apis/bae-charging-backend-test/src/media/bills
        - /your/assets/path:/apis/bae-charging-backend-test/src/media/assets
        - /your/plugins/path:/apis/bae-charging-backend-test/src/plugins
        - /your/indexes/path:/apis/bae-logic-proxy-test/indexes
    environment:
        - MYSQL_ROOT_PASSWORD=my-secret-pw
        - MYSQL_HOST=biz_db
        - OAUTH2_CLIENT_ID=your-client-id
        - OAUTH2_CLIENT_SECRET=your-client-secret
        - PAYPAL_CLIENT_ID=your-paypal-client-id
        - PAYPAL_CLIENT_SECRET=your-paypal-client-secret
        - ADMIN_EMAIL=your@email.com
        - BIZ_ECOSYS_PORT=8000
        - BIZ_ECOSYS_HOST=localhost
